### ISSUE TITLE
Pip subprocess error:

### ISSUE THREAD

**Issue by zxr111** [thunlp/ELLE#1]
Why occor error when install env
Pip subprocess error:
  Running command git clone -q https://github.com/kernelmachine/allennlp.git /tmp/pip-req-build-zsoedld9
  Running command git rev-parse -q --verify 'sha^4ae123d2c3bfb1ea3ce7362cb6c5bca3d094ffa7'
  Running command git fetch -q https://github.com/kernelmachine/allennlp.git 4ae123d2c3bfb1ea3ce7362cb6c5bca3d094ffa7
  Running command git checkout -q 4ae123d2c3bfb1ea3ce7362cb6c5bca3d094ffa7
ERROR: Cannot install -r /home/zxr/code/ELLE/condaenv.kk5i_96l.requirements.txt (line 1) and pytorch-transformers==1.2.0 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

failed

CondaEnvException: Pip failed

**Comment by Neo-Zhangjiajie** [comment]
Can you try that create a environment with conda and then install the three packages one by one with pip?

**Comment by Neo-Zhangjiajie** [comment]
Or you can install the allennlp as https://github.com/allenai/dont-stop-pretraining and then update the pytorch-transformers to 1.2.0.
