### ISSUE TITLE
Error: train.py: error: argument --task: invalid choice: 'continual_KI'

### ISSUE THREAD

**Issue by Vincent950129** [thunlp/ELLE#3]
Hi,

Thank you for the work. I am trying to run ELLE for pre-training with the script `train_base_prompt.sh` in `fairseq_ELLE\examples\roberta`. It complains 

`train.py: error: argument --task: invalid choice: 'continual_KI' (choose from 'sentence_prediction', 'language_modeling', 'speech_to_text', 'translation', 'multilingual_translation', 'semisupervised_translation', 'audio_pretraining', 'multilingual_masked_lm', 'cross_lingual_lm', 'denoising', 'multilingual_denoising', 'translation_from_pretrained_xlm', 'legacy_masked_lm', 'translation_multi_simple_epoch', 'masked_lm', 'translation_from_pretrained_bart', 'sentence_ranking', 'translation_lev', 'dummy_lm', 'dummy_masked_lm', 'dummy_mt')`

Which one I should choose in order to continual pre-train?

Thank you for your time.

**Comment by Neo-Zhangjiajie** [comment]
Could you try adding this commond before the bash:
`export PYTHONPATH=fairseq_ELLE`
You need to guarantee that you fairseq libary is from fairseq_ELLE.  Similarly, when you run code in fairseq-0.9.0, you need this commond:
`export PYTHONPATH=fairseq-0.9.0`
