### ISSUE TITLE
Hello,What's the CUDA version ?

### ISSUE THREAD

**Issue by Claymore715** [thunlp/ELLE#4]
ERROR: Command errored out with exit status 1:
     command: 'D:\anaconda3\envs\ELLE\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'D:\\Code\\tuimian_shixi\\ELLE-main\\fairseq_ELLE\\setup.py'"'"'; __file__='"'"'D:\\Code\\tuimian_shixi\\ELLE-main\\fairseq_ELLE\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: D:\Code\tuimian_shixi\ELLE-main\fairseq_ELLE\
    Complete output (25 lines):
    No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4'

**Comment by Neo-Zhangjiajie** [comment]
Our CUDA version is 11.2.

**Comment by Claymore715** [comment]
I have the problem"ERROR: Could not build wheels for allennlp which use PEP 517 and cannot be installed directly"  when I want to deploy it on the Colab, how could I fix it.

**Comment by Neo-Zhangjiajie** [comment]
It seems that updating pip and setuptools can solve this problem.
```
python -m pip install --upgrade pip
python -m pip install --upgrade setuptools
```
